import type { Item, Movement, WorkOrder } from "./types";

const DAY = 86_400_000;

export function createSeed(now = Date.now()): {
  items: Item[];
  movements: Movement[];
  orders: WorkOrder[];
} {
  const items: Item[] = [
    {
      id: "it-crepe-navy",
      name: "کرپ مازراتی سرمه‌ای",
      sku: "DB-F-001",
      category: "fabric",
      unit: "meter",
      quantity: 48,
      minQuantity: 12,
      color: "سرمه‌ای",
      widthCm: 150,
      composition: "پلی‌استر کرپ",
      location: "قفسه آ-۱",
      supplier: "پارچه‌سرای نساج",
      unitPrice: 285000,
      notes: "برای مانتو اداری. عرض کامل، بدون رگه.",
      createdAt: now - 40 * DAY,
      updatedAt: now - 1 * DAY,
    },
    {
      id: "it-crepe-black",
      name: "کرپ مازراتی مشکی",
      sku: "DB-F-002",
      category: "fabric",
      unit: "meter",
      quantity: 21,
      minQuantity: 12,
      color: "مشکی",
      widthCm: 150,
      composition: "پلی‌استر کرپ",
      location: "قفسه آ-۱",
      supplier: "پارچه‌سرای نساج",
      unitPrice: 285000,
      notes: "",
      createdAt: now - 40 * DAY,
      updatedAt: now - 2 * DAY,
    },
    {
      id: "it-linen-beige",
      name: "لینن طبیعی بژ",
      sku: "DB-F-003",
      category: "fabric",
      unit: "meter",
      quantity: 36,
      minQuantity: 10,
      color: "بژ",
      widthCm: 140,
      composition: "کتان / لینن",
      location: "قفسه آ-۲",
      supplier: "کتان شرق",
      unitPrice: 420000,
      notes: "آب‌رفت حدود ۳ درصد. قبل برش بخار بزنید.",
      createdAt: now - 28 * DAY,
      updatedAt: now - 3 * DAY,
    },
    {
      id: "it-cotton-stripe",
      name: "کتان راه‌راه آبی",
      sku: "DB-F-004",
      category: "fabric",
      unit: "meter",
      quantity: 8,
      minQuantity: 10,
      color: "آبی راه‌راه",
      widthCm: 145,
      composition: "پنبه ۱۰۰٪",
      location: "قفسه آ-۲",
      supplier: "کتان شرق",
      unitPrice: 310000,
      notes: "",
      createdAt: now - 20 * DAY,
      updatedAt: now - 1 * DAY,
    },
    {
      id: "it-satin-lining",
      name: "ساتن آستر کرم",
      sku: "DB-F-005",
      category: "fabric",
      unit: "meter",
      quantity: 62,
      minQuantity: 15,
      color: "کرم",
      widthCm: 150,
      composition: "پلی‌استر ساتن",
      location: "قفسه آ-۳",
      supplier: "پارچه‌سرای نساج",
      unitPrice: 145000,
      notes: "آستر مانتو و کت.",
      createdAt: now - 35 * DAY,
      updatedAt: now - 6 * DAY,
    },
    {
      id: "it-velvet",
      name: "مخمل کبریتی خردلی",
      sku: "DB-F-006",
      category: "fabric",
      unit: "meter",
      quantity: 6.5,
      minQuantity: 8,
      color: "خردلی",
      widthCm: 140,
      composition: "مخمل کبریتی",
      location: "قفسه آ-۳",
      supplier: "مخمل پارس",
      unitPrice: 560000,
      notes: "موجودی کم — برای کت پاییزه رزرو شده.",
      createdAt: now - 18 * DAY,
      updatedAt: now - 1 * DAY,
    },
    {
      id: "it-denim",
      name: "جین آبی تیره",
      sku: "DB-F-007",
      category: "fabric",
      unit: "meter",
      quantity: 15,
      minQuantity: 8,
      color: "آبی تیره",
      widthCm: 155,
      composition: "پنبه جین ۱۲ اونس",
      location: "قفسه آ-۴",
      supplier: "جین‌باف",
      unitPrice: 390000,
      notes: "",
      createdAt: now - 14 * DAY,
      updatedAt: now - 4 * DAY,
    },
    {
      id: "it-thread-black",
      name: "نخ پلی‌استر ۴۰/۲ مشکی",
      sku: "DB-T-001",
      category: "thread",
      unit: "spool",
      quantity: 24,
      minQuantity: 6,
      color: "مشکی",
      location: "کشو ن-۱",
      supplier: "نخ‌تاب",
      unitPrice: 38000,
      notes: "قرقره ۵۰۰۰ متری صنعتی.",
      createdAt: now - 50 * DAY,
      updatedAt: now - 8 * DAY,
    },
    {
      id: "it-thread-navy",
      name: "نخ پلی‌استر ۴۰/۲ سرمه‌ای",
      sku: "DB-T-002",
      category: "thread",
      unit: "spool",
      quantity: 11,
      minQuantity: 6,
      color: "سرمه‌ای",
      location: "کشو ن-۱",
      supplier: "نخ‌تاب",
      unitPrice: 38000,
      notes: "",
      createdAt: now - 50 * DAY,
      updatedAt: now - 5 * DAY,
    },
    {
      id: "it-thread-cream",
      name: "نخ پلی‌استر ۴۰/۲ کرم",
      sku: "DB-T-003",
      category: "thread",
      unit: "spool",
      quantity: 4,
      minQuantity: 6,
      color: "کرم",
      location: "کشو ن-۱",
      supplier: "نخ‌تاب",
      unitPrice: 38000,
      notes: "",
      createdAt: now - 22 * DAY,
      updatedAt: now - 2 * DAY,
    },
    {
      id: "it-zip-hidden",
      name: "زیپ مخفی ۲۰ سانتی مشکی",
      sku: "DB-Z-001",
      category: "zipper",
      unit: "piece",
      quantity: 80,
      minQuantity: 20,
      color: "مشکی",
      location: "کشو ز-۱",
      supplier: "یراق‌دوز",
      unitPrice: 12000,
      notes: "",
      createdAt: now - 30 * DAY,
      updatedAt: now - 9 * DAY,
    },
    {
      id: "it-zip-metal",
      name: "زیپ فلزی ۵۰ سانتی برنز",
      sku: "DB-Z-002",
      category: "zipper",
      unit: "piece",
      quantity: 18,
      minQuantity: 10,
      color: "برنز",
      location: "کشو ز-۱",
      supplier: "یراق‌دوز",
      unitPrice: 45000,
      notes: "برای کت و پالتو.",
      createdAt: now - 16 * DAY,
      updatedAt: now - 3 * DAY,
    },
    {
      id: "it-btn-shell",
      name: "دکمه صدفی ۱۸ میلی",
      sku: "DB-B-001",
      category: "button",
      unit: "piece",
      quantity: 240,
      minQuantity: 80,
      color: "طبیعی",
      location: "کشو د-۱",
      supplier: "یراق‌دوز",
      unitPrice: 2500,
      notes: "بسته ۱۰۰ تایی باز شده.",
      createdAt: now - 45 * DAY,
      updatedAt: now - 12 * DAY,
    },
    {
      id: "it-btn-black",
      name: "دکمه پایه‌دار مشکی ۲۲",
      sku: "DB-B-002",
      category: "button",
      unit: "piece",
      quantity: 64,
      minQuantity: 40,
      color: "مشکی",
      location: "کشو د-۱",
      supplier: "یراق‌دوز",
      unitPrice: 4000,
      notes: "",
      createdAt: now - 25 * DAY,
      updatedAt: now - 7 * DAY,
    },
    {
      id: "it-interfacing",
      name: "لایی چسبی ۹۰ سانتی",
      sku: "DB-I-001",
      category: "interfacing",
      unit: "meter",
      quantity: 18,
      minQuantity: 8,
      color: "سفید",
      widthCm: 90,
      composition: "لایی چسبی سبک",
      location: "قفسه آ-۵",
      supplier: "لایی‌باف",
      unitPrice: 95000,
      notes: "یقه و جیب مانتو.",
      createdAt: now - 33 * DAY,
      updatedAt: now - 4 * DAY,
    },
    {
      id: "it-elastic",
      name: "کش شلواری ۲ سانتی",
      sku: "DB-R-001",
      category: "trim",
      unit: "meter",
      quantity: 30,
      minQuantity: 10,
      color: "سفید",
      location: "کشو خ-۱",
      supplier: "یراق‌دوز",
      unitPrice: 18000,
      notes: "",
      createdAt: now - 19 * DAY,
      updatedAt: now - 6 * DAY,
    },
    {
      id: "it-bias",
      name: "نوار اریب کتان کرم",
      sku: "DB-R-002",
      category: "trim",
      unit: "meter",
      quantity: 12,
      minQuantity: 8,
      color: "کرم",
      location: "کشو خ-۱",
      supplier: "کتان شرق",
      unitPrice: 22000,
      notes: "",
      createdAt: now - 11 * DAY,
      updatedAt: now - 2 * DAY,
    },
    {
      id: "it-lace",
      name: "گیپور سفید حاشیه",
      sku: "DB-R-003",
      category: "trim",
      unit: "meter",
      quantity: 7,
      minQuantity: 5,
      color: "سفید",
      location: "کشو خ-۲",
      supplier: "خرج‌کار گل‌دوز",
      unitPrice: 85000,
      notes: "عرض ۶ سانتی.",
      createdAt: now - 9 * DAY,
      updatedAt: now - 1 * DAY,
    },
    {
      id: "it-needle",
      name: "سوزن صنعتی DB×1",
      sku: "DB-K-001",
      category: "tool",
      unit: "pack",
      quantity: 8,
      minQuantity: 3,
      color: "نقره‌ای",
      location: "کشو ابزار",
      supplier: "ماشین‌دوز صنعت",
      unitPrice: 65000,
      notes: "بسته ۱۰ تایی، سایز ۱۴.",
      createdAt: now - 60 * DAY,
      updatedAt: now - 15 * DAY,
    },
    {
      id: "it-magnet",
      name: "دکمه مغناطیسی پالتو",
      sku: "DB-B-003",
      category: "button",
      unit: "piece",
      quantity: 9,
      minQuantity: 12,
      color: "مشکی",
      location: "کشو د-۲",
      supplier: "یراق‌دوز",
      unitPrice: 18000,
      notes: "کمبود — سفارش بعدی را زود بزنید.",
      createdAt: now - 7 * DAY,
      updatedAt: now - 1 * DAY,
    },
  ];

  const movements: Movement[] = [
    {
      id: "mv-1",
      itemId: "it-crepe-navy",
      type: "in",
      quantity: 50,
      reason: "خرید جدید",
      createdAt: now - 12 * DAY,
    },
    {
      id: "mv-2",
      itemId: "it-crepe-navy",
      type: "out",
      quantity: 2,
      reason: "نمونه",
      createdAt: now - 8 * DAY,
    },
    {
      id: "mv-3",
      itemId: "it-cotton-stripe",
      type: "out",
      quantity: 6,
      reason: "مصرف سفارش",
      orderId: "wo-shirt-linen",
      createdAt: now - 3 * DAY,
    },
    {
      id: "mv-4",
      itemId: "it-thread-cream",
      type: "out",
      quantity: 2,
      reason: "مصرف سفارش",
      createdAt: now - 2 * DAY,
    },
    {
      id: "mv-5",
      itemId: "it-velvet",
      type: "out",
      quantity: 3.5,
      reason: "مصرف سفارش",
      orderId: "wo-velvet-coat",
      createdAt: now - 1 * DAY,
    },
    {
      id: "mv-6",
      itemId: "it-linen-beige",
      type: "in",
      quantity: 20,
      reason: "خرید جدید",
      createdAt: now - 3 * DAY,
    },
    {
      id: "mv-7",
      itemId: "it-magnet",
      type: "out",
      quantity: 6,
      reason: "مصرف سفارش",
      createdAt: now - 1 * DAY,
    },
    {
      id: "mv-8",
      itemId: "it-zip-metal",
      type: "in",
      quantity: 20,
      reason: "خرید جدید",
      createdAt: now - 5 * DAY,
    },
  ];

  const orders: WorkOrder[] = [
    {
      id: "wo-manteau",
      title: "مانتو اداری سرمه‌ای",
      customer: "فروشگاه نسیم",
      status: "cutting",
      dueDate: isoPlus(now, 5),
      lines: [
        { itemId: "it-crepe-navy", quantity: 18 },
        { itemId: "it-satin-lining", quantity: 16 },
        { itemId: "it-thread-navy", quantity: 2 },
        { itemId: "it-interfacing", quantity: 4 },
        { itemId: "it-btn-black", quantity: 24 },
      ],
      notes: "۸ عدد، قد ۱۱۵، سایز ۳۶ تا ۴۴. یقه ایستاده.",
      consumed: false,
      createdAt: now - 4 * DAY,
      updatedAt: now - 1 * DAY,
    },
    {
      id: "wo-shirt-linen",
      title: "شومیز لینن بژ",
      customer: "آتلیه مهتاب",
      status: "sewing",
      dueDate: isoPlus(now, 2),
      lines: [
        { itemId: "it-linen-beige", quantity: 14 },
        { itemId: "it-thread-cream", quantity: 2 },
        { itemId: "it-btn-shell", quantity: 36 },
      ],
      notes: "۱۲ عدد. آستین بلند، دکمه صدفی.",
      consumed: true,
      createdAt: now - 6 * DAY,
      updatedAt: now - 2 * DAY,
    },
    {
      id: "wo-velvet-coat",
      title: "کت مخمل خردلی",
      customer: "سفارش شخصی — خانم رضایی",
      status: "draft",
      dueDate: isoPlus(now, 12),
      lines: [
        { itemId: "it-velvet", quantity: 4 },
        { itemId: "it-satin-lining", quantity: 3.5 },
        { itemId: "it-zip-metal", quantity: 2 },
        { itemId: "it-magnet", quantity: 4 },
      ],
      notes: "۲ عدد. مغزی خردلی، آستر کرم.",
      consumed: false,
      createdAt: now - 2 * DAY,
      updatedAt: now - 2 * DAY,
    },
  ];

  return { items, movements, orders };
}

function isoPlus(now: number, days: number) {
  const d = new Date(now + days * DAY);
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${d.getFullYear()}-${m}-${day}`;
}
