/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoveRouteImport } from './routes/move'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as StockIndexRouteImport } from './routes/stock.index'
import { Route as StockItemIdRouteImport } from './routes/stock.$itemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoveRoute = MoveRouteImport.update({
  id: '/move',
  path: '/move',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const StockIndexRoute = StockIndexRouteImport.update({
  id: '/stock/',
  path: '/stock/',
  getParentRoute: () => rootRouteImport,
} as any)
const StockItemIdRoute = StockItemIdRouteImport.update({
  id: '/stock/$itemId',
  path: '/stock/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/move': typeof MoveRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/stock/$itemId': typeof StockItemIdRoute
  '/orders/': typeof OrdersIndexRoute
  '/stock/': typeof StockIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/move': typeof MoveRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/stock/$itemId': typeof StockItemIdRoute
  '/orders': typeof OrdersIndexRoute
  '/stock': typeof StockIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/move': typeof MoveRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/stock/$itemId': typeof StockItemIdRoute
  '/orders/': typeof OrdersIndexRoute
  '/stock/': typeof StockIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/move'
    | '/orders/$orderId'
    | '/stock/$itemId'
    | '/orders/'
    | '/stock/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/move' | '/orders/$orderId' | '/stock/$itemId' | '/orders' | '/stock'
  id:
    | '__root__'
    | '/'
    | '/move'
    | '/orders/$orderId'
    | '/stock/$itemId'
    | '/orders/'
    | '/stock/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MoveRoute: typeof MoveRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  StockItemIdRoute: typeof StockItemIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  StockIndexRoute: typeof StockIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/move': {
      id: '/move'
      path: '/move'
      fullPath: '/move'
      preLoaderRoute: typeof MoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/': {
      id: '/stock/'
      path: '/stock'
      fullPath: '/stock/'
      preLoaderRoute: typeof StockIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/$itemId': {
      id: '/stock/$itemId'
      path: '/stock/$itemId'
      fullPath: '/stock/$itemId'
      preLoaderRoute: typeof StockItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MoveRoute: MoveRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  StockItemIdRoute: StockItemIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  StockIndexRoute: StockIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
